### ISSUE TITLE
Backrefs not generated

### ISSUE THREAD

**Issue by miracle2k** [jelz/cf-graphql#3]
My backrefs are not generated. It seems this is because the /content_types API of the CDA does not list the validations, for example:

    "fields": [
      {
        "id": "backend",
        "name": "Backend",
        "type": "Symbol",
        "localized": false,
        "required": true,
        "disabled": false,
        "omitted": false
      },
      {
        "id": "productGroup",
        "name": "Product Group",
        "type": "Link",
        "localized": false,
        "required": false,
        "disabled": false,
        "omitted": false,
        "linkType": "Entry"
      },
      ...

This is an actual result I get from https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/content-types/content-model

But looking at the JSON preview in the Contentful UI, I actually see the validation:

    {
      "name": "Product Group",
      "id": "productGroup",
      "type": "Link",
      "linkType": "Entry",
      "validations": [
        {
          "linkContentType": [
            "productGroup"
          ]
        }
      ]
    },

**Comment by miracle2k** [comment]
If I run prepareCts with the output of the content management API, everything seems fine.

**Comment by jelz** [comment]
Just to verify: are you sure your content type is published? `validations` key should be present in CDA responses.

**Comment by miracle2k** [comment]
It's very possible you are right. In fact, if you say it, I believe you. I noticed the other day that one of my content types was in "updated" state, which for some reason I didn't notice before. I probably got confused. If I have problems again, I will open another ticket.
