### ISSUE TITLE
Single content type queries

### ISSUE THREAD

**Issue by otbe** [jelz/cf-graphql#8]
Hi,

discovered cf-graphql some days ago and it works pretty well with our production cf space! 👍 
One problem arises from your docs or our content model. Imagine we have a model called ```app``` with a contact field on it. This contact field is a one-to-one reference to a model called ```Contact``` (only this model is an accepted content type).

After reading your docs I tried the following query:
```graphql
query {
  apps {
    contact {
       name
    }
  }
}
```
but it didn't work. So I tried 

```graphql
query {
  apps {
    contact {
      ...on Contact {
        name
      }
    }
  }
}
```
This time I get my expected response. What kind of relation enables the simple query? I thought a one-to-one relation with a single accepted content type should be enough :)

Thanks so far!

**Comment by jelz** [comment]
This is a duplicate of #6 and will be fixed in v0.3 release

**Comment by otbe** [comment]
Yeah I thought this is caused by the same issue. Thanks for clarifying this :)

**Comment by jelz** [comment]
@otbe reopened for verification: could you please check if v0.3 solves the problem for you?

**Comment by otbe** [comment]
Sorry, forget to answer yesterday :)

Yes it works as expected!
